Repository mayankchaudhary26/HacktoberFest-Practice-2021, pull requests merged in 2021-10, with the labels that each got.

#39 Add a Project
  WordCloud/WordCloud.py
Labels: hacktoberfest-accepted

#40 Added a project
  Desktop Battery Notifier.py
Labels: hacktoberfest-accepted

#41 Create number guessing game.py
  number guessing game.py
Labels: hacktoberfest-accepted

#42 Simple linear Regression in python i.e data science
  Data_science/Simple linear Regression.py
Labels: hacktoberfest-accepted

#43 Python Program for Legendre\’s Conjecture
  Legendre\’s_Conjecture.py
Labels: hacktoberfest-accepted

#44 Added a python program
  password_validity.py
Labels: hacktoberfest-accepted

#45 1-Create Age and gender detection.py
  Age and gender detection.py
Labels: hacktoberfest-accepted

#46 2-Update Age and gender detection.py
  Age and gender detection.py
Labels: hacktoberfest-accepted

#47 3-Update Age and gender detection.py
  Age and gender detection.py
Labels: hacktoberfest-accepted

#48 4-Update Age and gender detection.py
  Age and gender detection.py
Labels: hacktoberfest-accepted

#50 1-Create Alarm clock.py
  Alarm clock.py
Labels: hacktoberfest-accepted

#52 2-Update Alarm clock.py
  Alarm clock.py
Labels: hacktoberfest-accepted

#54 3-Update Alarm clock.py
  Alarm clock.py
Labels: hacktoberfest-accepted

#55 4-Update Alarm clock.py
  Alarm clock.py
Labels: hacktoberfest-accepted

#49 Added Uno-Card-Game.py
  Uno-Card-Game.py
Labels: hacktoberfest-accepted

#51 Create Largest_Rectangle_Of_0.py
  Largest_Rectangle_Of_0.py
Labels: hacktoberfest-accepted

#53 Car lease menu based application using python
  Car lease menu based application using python/123_amortization_table.txt
  Car lease menu based application using python/125_amortization_table.txt
  Car lease menu based application using python/Car lease menu based application code.ipynb
  Car lease menu based application using python/Readme.md
  Car lease menu based application using python/customer.txt
  Car lease menu based application using python/readme.md
Labels: hacktoberfest-accepted

#56 Create tree_design_based_on_input.py
  tree_design_based_on_input.py
Labels: hacktoberfest-accepted

#57 Takes user input now
  password_validity.py
Labels: hacktoberfest-accepted

#58 Added Python programs and Snake Game project
  Age and gender detection.py
  Alarm clock.py
  BMI Calculator.py
  Car lease menu based application using python/123_amortization_table.txt
  Car lease menu based application using python/125_amortization_table.txt
  Car lease menu based application using python/Car lease menu based application code.ipynb
  Car lease menu based application using python/Readme.md
  Car lease menu based application using python/customer.txt
  Car lease menu based application using python/readme.md
  Clock GUI.py
  Data_science/Simple linear Regression.py
  Desktop Battery Notifier.py
  Dice Roll Simulator.py
  Fidget spinner.py
  Hangman.py
  Largest_Rectangle_Of_0.py
  Legendre\’s_Conjecture.py
  Music player GUI.py
  Quiz game.py
  README.md
  Rock-paper-scissors.py
  Scientific Calculator.py
  Uno-Card-Game.py
  WordCloud/WordCloud.py
  binary_to_decimal.py
  binarysearch.py
  bubble_sort_1.py
  consogram.py
  currency-converter-project.py
  number guessing game.py
  password_validity.py
  reversedlinkedlist.py
  snake game.py
  snakegame.py
  tree_design_based_on_input.py
Labels: hacktoberfest-accepted

#59 Create Clock_GUI.py
  Clock_GUI.py
Labels: hacktoberfest-accepted

#60 Create UnitConverter.py
  UnitConverter.py
Labels: hacktoberfest-accepted

#61 Create GCD.py
  GCD.py
Labels: hacktoberfest-accepted

#62 python code to generate spinning donut
  donut.py
Labels: hacktoberfest-accepted

#63 Added Pre_fix_Sum
  pre_fix_sum.py
Labels: hacktoberfest-accepted

#64 added bfs
  bfs.py
Labels: hacktoberfest-accepted

#66 Added Merge Sort code
  merge_sort.py
Labels: hacktoberfest-accepted

#67 1-Create Number Guessing game.py
  Number Guessing game.py
Labels: hacktoberfest-accepted

#68 2-Update Number Guessing game.py
  Number Guessing game.py
Labels: hacktoberfest-accepted

#69 3-Update Number Guessing game.py
  Number Guessing game.py
Labels: hacktoberfest-accepted

#70 4-Update Number Guessing game.py
  Number Guessing game.py
Labels: hacktoberfest-accepted

#71 Analog clock in Python
  Analog_Clock.py
Labels: hacktoberfest-accepted

#72 Added a pyramid.py file
  pyramid.py
Labels: hacktoberfest-accepted

#73 Added binary search tree code
  binary_search_tree.py
  circular_linked_list.py
  doubly_linked_list.py
  selection_sort.py
  stack_array.py
Labels: hacktoberfest-accepted

#74 Rock, paper or Scissors?
  rock_paper_scissors.py
Labels: hacktoberfest-accepted

#75 python code to turn text into handwritten text
  text-handtext.py
Labels: hacktoberfest-accepted

#76 String reversal using recursion
  recursion_reversal.py
Labels: hacktoberfest-accepted

#77 Insertion sort advanced analysis
  insertionsortanalysis.py
Labels: hacktoberfest-accepted

#78 Added Python Project
  Turtle Race.py
Labels: hacktoberfest-accepted

#81 Connect Four Game - Python
  connect_four_game.py
Labels: hacktoberfest-accepted

#79 Made a python program that suggests different activities to do
  activity_suggestor.py
Labels: hacktoberfest-accepted

#82 Algorithms added
  Floyd.py
  Horspool_Algorithm.py
  closestPairProblem.py
  heapsort.py
  quickSort.py
Labels: hacktoberfest-accepted

#83 ToDo Script
  ToDo.py
Labels: hacktoberfest-accepted

#84 added month_calander
  month_calander.py
Labels: hacktoberfest-accepted

#85 Removal of duplicate elements in circular linked list
  removal_ofduplicates_incircular_linkedlist.py
Labels: hacktoberfest-accepted

#80 added a code of prime using EOF
  prime_using_sieve_of_eratosthenes.py
Labels: hacktoberfest-accepted

#86 Fibonacci Series with a Twist.py
  Fibonacci Series with a Twist
Labels: hacktoberfest-accepted

#87 added matrix effect with python script
  matrix_effect.py
Labels: hacktoberfest-accepted

#88 added simple password hashing
  simple_password_hashing.py
Labels: hacktoberfest-accepted

#90 added checkbit operation
  bit_operation_checkbit.py
Labels: hacktoberfest-accepted

#92 Program_to_find_substring
  Find a string.py
  swap_case.py
Labels: hacktoberfest-accepted

#95 Language Translator with Python
  Language Translater.py
Labels: hacktoberfest-accepted

#97 Created armstrong_checker.py
  armstrong_checker.py
Labels: hacktoberfest-accepted

#98 Bulk Image resizer
  resize.py
Labels: hacktoberfest-accepted

#100 Added Random password generator
  randompasswordgenerator.py
Labels: hacktoberfest-accepted

#102 invisibility cloak from harry potter (open cv)
  invisibility_cloak.py
Labels: good first issue, hacktoberfest-accepted

#103 Diamond-Shaped Pattern
  diamond_pattern.py
Labels: hacktoberfest-accepted

#96 Base and Power -Using Recursive Function.py
  Base and Power -Using Recursive Function
Labels: good first issue, hacktoberfest-accepted

#104 Added a script for quotes scraping
  quote_scrap.py
Labels: good first issue, hacktoberfest-accepted

#94 Added Vaccine Slot Program
  GetVaccineSlot.py
Labels: good first issue, hacktoberfest-accepted

#107 Added gui-calculator
  guicalculator.py
Labels: good first issue, hacktoberfest-accepted, Basic program

#105 Kruskal Algorithm
  KruskalAlgo.py
Labels: good first issue, hacktoberfest-accepted, Basic program, Python

#106 Maximum Product Subarray
  MaxSubarrayProduct.py
Labels: hacktoberfest-accepted, Basic program, Python

#108 Python script for checking live CoVID19 cases
  Covid19_Info.py
Labels: hacktoberfest-accepted, Python

#99 add dfs
  dfs.py
Labels: hacktoberfest-accepted, Basic program

#109 Create squareUsingBitOp.cpp
  squareUsingBitOp.cpp
Labels: good first issue, hacktoberfest-accepted, C++

#110 Create subsequence.cpp
  subsequence.cpp
Labels: hacktoberfest-accepted, C++

#112 Python script for scraping search results for a item.
  Scrap-Amazon.py
Labels: hacktoberfest-accepted, Python

#114 Rat_in_a_Maze.java
  Rat_in_a_Maze.java
Labels: good first issue, hacktoberfest-accepted, Java

#113 Sort_012.java
  Sort_012.java
Labels: hacktoberfest-accepted, Java

#116 Booth's algorithm implementation
  Booth's_Algorithm.py
Labels: hacktoberfest-accepted, Python

#122 Add Pre-order Traversal
  PreorderTraversal.py
Labels: hacktoberfest-accepted, Python

#123 Count_Down_Timer.py
  Count_Down_Timer
Labels: hacktoberfest-accepted, Python

#121 add inorder_traversal
  inorder_traversal.py
Labels: hacktoberfest-accepted, Python

#115 Created Convert2JPG.py
  Convert2JPG.py
Labels: hacktoberfest-accepted, Basic program, Python

#126 Create Palindrome. py
  Palindrome. py
Labels: hacktoberfest-accepted, Basic program, Python

#127 Dynamic Programming Basic
  LCS.cpp
Labels: good first issue, hacktoberfest-accepted, C++

#125 X-Star_Pattern.py
  X-Star_Pattern.py
Labels: hacktoberfest-accepted, Basic program, Python

#130 classify and count
  Classify&count.py
Labels: hacktoberfest-accepted, Basic program, Python

#132 Merge_Two_Sorted_Array.java
  Merge_Two_Sorted_Array.java
Labels: hacktoberfest-accepted, Java

#129 Add a C++ program to reverse a Linked List
  reverseLinkedList.cpp
Labels: hacktoberfest-accepted, Basic program, C++

#131 Duplicate_Brackets.java
  Duplicate_Brackets.java
Labels: hacktoberfest-accepted, Basic program, Java

#134 Merge_Sort.java
  MergeSort.java
Labels: hacktoberfest-accepted, Basic program, Java

#133 Three_Sum_Problem
  ThreeSum.java
Labels: hacktoberfest-accepted, Java

#135 Quick_Sort.java
  Quick_Sort.java
Labels: hacktoberfest-accepted, Java

#117 Diamond_pattern
  Diamond_python.py
Labels: hacktoberfest-accepted, Basic program, Python

#120 Program_to_Swap_Cases
  swap_case.py
Labels: good first issue, hacktoberfest-accepted, Python

#137 Create BubbleSort.c
  BubbleSort.c
Labels: good first issue, hacktoberfest-accepted, C

#136 SmallestLetterGreaterthanTarget
  SmallestLetterGreaterthanTarget
Labels: hacktoberfest-accepted, Basic program, Python

#141 Create Text Similarity Script
  testSimilarity.py
Labels: good first issue, hacktoberfest-accepted, Python

#140 Currency convertor using forex library in python
  currency_convertor.py
Labels: hacktoberfest-accepted, Python

#138 Create isomorphicstrings.py
  isomorphicstrings.py
Labels: good first issue, hacktoberfest-accepted, Basic program, Python

#139 Find position element sorted array infinite numbers
  InfiniteArray.java
Labels: good first issue, hacktoberfest-accepted, Basic program, Java

#142 Create MatrixMultiplication.py
  MatrixMultiplication.py
Labels: hacktoberfest-accepted, Basic program, Python

#143 Added Caesar-cipher.py
  Caesar-cipher.py
Labels: good first issue, hacktoberfest-accepted, Basic program, Python

#146 Added Gas Station problem in CPP
  gasStation.cpp
Labels: hacktoberfest-accepted, C++

#148 Create nQueen.py
  nQueen.py
Labels: hacktoberfest-accepted, Python

#150 Create BubbleSort.java
  BubbleSort.java
Labels: hacktoberfest-accepted, Basic program, Java

#151 Added Tic-Tac-Toe Game using python
  tictactoe.py
Labels: hacktoberfest-accepted, Basic program, Python

#153 Added Hangman game using python
  Hangman/hangman_art.py
  Hangman/hangman_words.py
  Hangman/main.py
Labels: hacktoberfest-accepted, Python

#156 added a Dice program which was made using Python and Turtle
  dice.py
Labels: hacktoberfest-accepted, Python

#152 Create ShellSort.java
  ShellSort.java
Labels: hacktoberfest-accepted, Java

#158 chat bot by the name of jarvis
  jarvis.py
Labels: hacktoberfest-accepted, Python

#157 Insertion Sort Algorithm
  Insertion Sort.java
Labels: good first issue, hacktoberfest-accepted, Java

#163 ATMinterface in Java
  ATMInterface.java
Labels: hacktoberfest-accepted, Java

#164 Password Generator
  passwordGenerator.py
Labels: hacktoberfest-accepted, Basic program, Python

#161 Anagram
  Anagram.cpp
Labels: hacktoberfest-accepted, Basic program, C++

#159 Binary Search Algorithm
  BinarySearch.java
Labels: hacktoberfest-accepted, Basic program, Java

#160 Added a program to find the equilibrium point in array
  Equilibrium_point.cpp
Labels: hacktoberfest-accepted, Basic program, C++

#162 Added seconds_calculator.py
  seconds_calculator.py
Labels: hacktoberfest-accepted, Basic program, Python

#155 Create Find_LCM_of_Two_Numbers.py
  Find_LCM_of_Two_Numbers.py
Labels: hacktoberfest-accepted, Basic program, Python

#147 Shift Reduce Parsing using C
  Shift Reduce Parsing.c
Labels: hacktoberfest-accepted, C

#171 Added IP Address Validator in CPP
  ip_address_validator.cpp
Labels: hacktoberfest-accepted, C++

#170 Added Linear Search
  linear_search.py
Labels: hacktoberfest-accepted, Basic program, Python

#172 Queue program using Array
  Queue_using_array.cpp
Labels: hacktoberfest-accepted, Basic program, C++

#167 Added Fibonacci.java file
  Fibonacci Series.java
Labels: good first issue, hacktoberfest-accepted, Basic program, Java

#168 Added a program of pascal triangle in c++
  pascaltriangle.cpp
Labels: hacktoberfest-accepted, Basic program, C++

#174 Palindrome number in Java
  Palindrome.java
Labels: hacktoberfest-accepted, Basic program, Java

#169 Find Weather Info
  Weather.py
Labels: hacktoberfest-accepted, Python

#166 Create Reverse_Circular_Doubly_Linklist.py
  Reverse_Circular_Doubly_Linklist.py
Labels: hacktoberfest-accepted, Python

#165 FindElementInSortedArrayOfInfiniteLength.java
  FindElementInSortedArrayOfInfiniteLength.java
Labels: hacktoberfest-accepted, Java

#154 Update rock_paper_scissors.py
  rock_paper_scissors.py
Labels: enhancement, hacktoberfest-accepted

#176 Create Trapping Rainwater Problem.cpp
  Trapping Rainwater Problem.cpp
Labels: hacktoberfest-accepted, C++

#180 Add files via upload
  Armstrong.py
Labels: hacktoberfest-accepted, Basic program, Python

#178 Create decimaltobinary.cpp
  decimaltobinary.cpp
Labels: good first issue, hacktoberfest-accepted, Basic program, C++

#179 Inverted Triangle Pattern Program
  InvertedTriangle.java
Labels: hacktoberfest-accepted, Java

#182 added Balanced string
  A_Balanced_Substring.cpp
  A_Balanced_Substring.exe
Labels: hacktoberfest-accepted, C++

#177 Add files via upload
  search.py
Labels: hacktoberfest-accepted, Basic program, Python

#186 3 solutions-Largest Substr Without Repeating Character
  LargestSubstrWithoutRepeatingChar.cpp
Labels: hacktoberfest-accepted, C++

#183 Adding Armstrong number. c
  Armstrong number. c
Labels: hacktoberfest-accepted, Basic program, C

#187 Create topologicalSort.cpp
  topologicalSort.cpp
Labels: hacktoberfest-accepted, C++

#188 Python Program to Extract Unique values dictionary values
  uniquevalus.py
Labels: good first issue, hacktoberfest-accepted, Basic program, Python

#184 Added a shape detection code in python
  Shape Detection.py
Labels: hacktoberfest-accepted, Python

#189 Create randomquotegenerator.py
  randomquotegenerator.py
Labels: hacktoberfest-accepted, Basic program, Python

#193 Create Permutation by python
  permutation.py
Labels: hacktoberfest-accepted, Basic program, Python

#192 Added Calculator Tkinter Program
  calculator.py
Labels: good first issue, hacktoberfest-accepted, Python

#196 Created sWAP_cASE.py
  sWAP_cASE.py
Labels: hacktoberfest-accepted, Basic program, Python

#195 Adding Stock Span Problem
  stock_span_problem.cpp
Labels: hacktoberfest-accepted, C++

#201 Create heap sort by C
  heapsort.c
Labels: hacktoberfest-accepted, Basic program, C

#200 Create factorial.py
  factorial.py
Labels: hacktoberfest-accepted, Basic program, Python

#206 SpeechRecognition.py
  SpeechRecognition.py
Labels: good first issue, hacktoberfest-accepted, Python

#205 Soccer Game.py
  Soccer Game.py
Labels: hacktoberfest-accepted, Python

#203 Tic Tac Toe Game.py
  Tic Tac Toe Game.py
Labels: hacktoberfest-accepted, Python

#202 feat: dijkstra in python
  dijkstra.py
Labels: hacktoberfest-accepted, Python

#197 Added Implementation of Floyd's Algorithm.
  floyd's_algo.c
Labels: hacktoberfest-accepted, C

#199 Create Generate randomness game
  Generate randomness game.py
Labels: hacktoberfest-accepted, Python

#207 Java Calculator
  Calculator.java
Labels: hacktoberfest-accepted, Basic program, Java

#208 Add files via upload
  Calender for given year and month.py
Labels: hacktoberfest-accepted, Basic program, Python

#204 HANGMAN GAME.py
  HANGMAN GAME.py
Labels: hacktoberfest-accepted, Python

#185 Create BublesOut.py
  Bubble sort.py
Labels: hacktoberfest-accepted, Basic program, Python
